// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"sync"
)

// Ensure, that OrderRepositoryMock does implement OrderRepository.
// If this is not the case, regenerate this file with moq.
var _ OrderRepository = &OrderRepositoryMock{}

// OrderRepositoryMock is a mock implementation of OrderRepository.
//
//	func TestSomethingThatUsesOrderRepository(t *testing.T) {
//
//		// make and configure a mocked OrderRepository
//		mockedOrderRepository := &OrderRepositoryMock{
//			FindByIdFunc: func(id string) Order {
//				panic("mock out the FindById method")
//			},
//			GetAllFunc: func() []Order {
//				panic("mock out the GetAll method")
//			},
//			StoreFunc: func(order Order) error {
//				panic("mock out the Store method")
//			},
//		}
//
//		// use mockedOrderRepository in code that requires OrderRepository
//		// and then make assertions.
//
//	}
type OrderRepositoryMock struct {
	// FindByIdFunc mocks the FindById method.
	FindByIdFunc func(id string) Order

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func() []Order

	// StoreFunc mocks the Store method.
	StoreFunc func(order Order) error

	// calls tracks calls to the methods.
	calls struct {
		// FindById holds details about calls to the FindById method.
		FindById []struct {
			// ID is the id argument value.
			ID string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
		}
		// Store holds details about calls to the Store method.
		Store []struct {
			// Order is the order argument value.
			Order Order
		}
	}
	lockFindById sync.RWMutex
	lockGetAll   sync.RWMutex
	lockStore    sync.RWMutex
}

// FindById calls FindByIdFunc.
func (mock *OrderRepositoryMock) FindById(id string) Order {
	if mock.FindByIdFunc == nil {
		panic("OrderRepositoryMock.FindByIdFunc: method is nil but OrderRepository.FindById was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockFindById.Lock()
	mock.calls.FindById = append(mock.calls.FindById, callInfo)
	mock.lockFindById.Unlock()
	return mock.FindByIdFunc(id)
}

// FindByIdCalls gets all the calls that were made to FindById.
// Check the length with:
//
//	len(mockedOrderRepository.FindByIdCalls())
func (mock *OrderRepositoryMock) FindByIdCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockFindById.RLock()
	calls = mock.calls.FindById
	mock.lockFindById.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *OrderRepositoryMock) GetAll() []Order {
	if mock.GetAllFunc == nil {
		panic("OrderRepositoryMock.GetAllFunc: method is nil but OrderRepository.GetAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc()
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedOrderRepository.GetAllCalls())
func (mock *OrderRepositoryMock) GetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// Store calls StoreFunc.
func (mock *OrderRepositoryMock) Store(order Order) error {
	if mock.StoreFunc == nil {
		panic("OrderRepositoryMock.StoreFunc: method is nil but OrderRepository.Store was just called")
	}
	callInfo := struct {
		Order Order
	}{
		Order: order,
	}
	mock.lockStore.Lock()
	mock.calls.Store = append(mock.calls.Store, callInfo)
	mock.lockStore.Unlock()
	return mock.StoreFunc(order)
}

// StoreCalls gets all the calls that were made to Store.
// Check the length with:
//
//	len(mockedOrderRepository.StoreCalls())
func (mock *OrderRepositoryMock) StoreCalls() []struct {
	Order Order
} {
	var calls []struct {
		Order Order
	}
	mock.lockStore.RLock()
	calls = mock.calls.Store
	mock.lockStore.RUnlock()
	return calls
}
